name: covid_tracker
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  easy_localization: ^2.3.3
  get_it: ^4.0.4
  provider: ^4.3.2
  dio: ^3.0.10
  ansicolor: ^1.0.2
  flutter_dotenv: ^2.1.0
  logger: ^0.9.2
  google_fonts: ^1.1.0
  flare_flutter: ^2.0.6
  flutter_swiper: ^1.1.6
  flutter_echarts: ^1.3.5
  rxdart: ^0.24.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/animation/
    - assets/fonts/
    - assets/locales/
    - assets/images/

